<?php

/**
 * Alunoturma
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Alunoturma extends BaseAlunoturma{
public function getIdAlunoTurma() {
		return $this->idAlunoTurma;
	}
	public function setIdAlunoTurma($idAlunoTurma) {
		$this->idAlunoTurma = $idAlunoTurma;
		return $this;
	}
	public function getIdAluno() {
		return $this->idAluno;
	}
	public function setIdAluno($idAluno) {
		$this->idAluno = $idAluno;
		return $this;
	}
	public function getIdTurma() {
		return $this->idTurma;
	}
	public function setIdTurma($idTurma) {
		$this->idTurma = $idTurma;
		return $this;
	}
	public function getAno() {
		return $this->ano;
	}
	public function setAno($ano) {
		$this->ano = $ano;
		return $this;
	}
	public function getAluno() {
		return $this->Aluno;
	}
	public function setAluno($Aluno) {
		$this->Aluno = $Aluno;
		return $this;
	}
	public function getTurma() {
		return $this->Turma;
	}
	public function setTurma($Turma) {
		$this->Turma = $Turma;
		return $this;
	}
	
	public function retornaAlunosDeTurma($idTurma){
		try{
			return $this->getTable('alunoturma')->findBy('idTurma', $idTurma);
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
}