<?php

/**
 * Aluno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Aluno extends BaseAluno{
	public function getIdAluno() {
		return $this->idAluno;
	}
	public function setIdAluno($idAluno) {
		$this->idAluno = $idAluno;
		return $this;
	}
	public function getNomeAluno() {
		return $this->nomeAluno;
	}
	public function setNomeAluno($nomeAluno) {
		$this->nomeAluno = $nomeAluno;
		return $this;
	}
	public function getEmailAluno() {
		return $this->emailAluno;
	}
	public function setEmailAluno($emailAluno) {
		$this->emailAluno = $emailAluno;
		return $this;
	}
	public function getAlunoturma() {
		return $this->Alunoturma;
	}
	public function setAlunoturma($Alunoturma) {
		$this->Alunoturma = $Alunoturma;
		return $this;
	}
	public function getResponde() {
		return $this->Responde;
	}
	public function setResponde($Responde) {
		$this->Responde = $Responde;
		return $this;
	}
	public function getIdProfessor() {
		return $this->idProfessor;
	}
	public function setIdProfessor($idProfessor) {
		$this->idProfessor = $idProfessor;
		return $this;
	}
	public function getProfessor() {
		return $this->Professor;
	}
	public function setProfessor($Professor) {
		$this->Professor = $Professor;
		return $this;
	}
	public function getParecer() {
		return $this->parecer;
	}
	public function setParecer($parecer) {
		$this->parecer = $parecer;
		return $this;
	}
	
	public function inserirAluno(){
		try{
			$this->save();
			return true;
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornaTodosAlunos(){
		try{
			$rs = $this->getTable("aluno")->findAll();
			return $rs;
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function excluirDisciplina(){
		try{
			$aluno = $this->getTable('aluno')->find($this->getIdAluno());
			if($aluno){
				$aluno->delete();
				return true;
			} else {
				return false;
			}
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function atualizarAluno(){
		try{
			$aluno = $this->getTable('aluno')->find($this->getIdAluno());
			if($aluno){
				if(!is_null($this->getIdAluno())){
					$aluno->setIdAluno($this->getIdAluno());
				}
				if(!is_null($this->getNomeAluno())){
					$aluno->setNomeAluno($this->getNomeAluno());
				}
				if(!is_null($this->getEmailAluno())){
					$aluno->setEmailAluno($this->getEmailAluno());
				}
				if(!is_null($this->getParecer())){
					$aluno->setParecer($this->getParecer());
				}
				$aluno->save();
				return true;
			} else {
				return false;
			}
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornaAlunoPorId(){
		try{
			return $this->getTable("aluno")->findOneBy('idAluno', $this->getIdAluno());
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornarPresencasEmTurma($idTurma){
		try{
			$tb = Doctrine_Core::getTable('Frequencia')->createQuery()
								->select('f.presenca')
								->from('frequencia f, aluno a, planejaementa p, turma t')
								->where('f.idAluno = a.idAluno AND f.idPlanejamento = p.idPlanejaEmenta AND p.idTurma = t.idTurma AND p.idTurma = '.$idTurma.' AND f.idAluno = '.$this->getIdAluno())
								->orderBy('p.previsto');
			return $tb->execute();
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	function getJson(){
		$array = Array();
		$array['idAluno'] = utf8_encode($this->idAluno);
		$array['nomeAluno'] = utf8_encode($this->nomeAluno);
		$array['emailAluno'] = utf8_encode($this->emailAluno);
	
		return json_encode($array);
	}
}