<?php

/**
 * Alunoturma
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Alunoturma extends BaseAlunoturma{
	public function getIdAlunoTurma(){
		return $this->idAlunoTurma;
	}
	
	public function getIdAluno(){
		return $this->idAluno;
	}
	
	public function getIdTurma(){
		return $this->idTurma();
	}
	
	public function setIdAlunoTurma($idAlunoTurma){
		$this->idAlunoTurma = $idAlunoTurma;
	}
	
	public function setIdAluno($idAluno){
		$this->idAluno = $idAluno;
	}
	
	public function setIdTurma($idTurma){
		$this->idTurma = $idTurma;
	}
	
	public function retornaAlunosDeTurma($idTurma){
		try{
			return $this->getTable('alunoturma')->findBy('idTurma', $idTurma);
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
}