<?php

/**
 * Aluno
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Aluno extends BaseAluno{
	public function getIdAluno(){
		return $this->idAluno;
	}
	
	public function getNomeAluno(){
		return $this->nomeAluno;
	}
	
	public function getEmailAluno(){
		return $this->emailAluno; 
	}
	
	public function setIdAluno($idAluno){
		$this->idAluno = $idAluno;
	}
	
	public function setNomeAluno($nomeAluno){
		$this->nomeAluno = $nomeAluno;
	}
	
	public function setEmailAluno($emailAluno){
		$this->emailAluno = $emailAluno;
	}
	
	public function inserirAluno(){
		try{
			$this->save();
			return true;
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornaTodosAlunos(){
		try{
			$rs = $this->getTable("aluno")->findAll();
			return $rs;
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function excluirDisciplina(){
		try{
			$aluno = $this->getTable('aluno')->find($this->getIdAluno());
			if($aluno){
				$aluno->delete();
				return true;
			} else {
				return false;
			}
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function atualizarAluno(){
		try{
			$aluno = $this->getTable('aluno')->find($this->getIdAluno());
			if($aluno){
				if(!is_null($this->getIdAluno())){
					$aluno->setIdAluno($this->getIdAluno());
				}
				if(!is_null($this->getNomeAluno())){
					$aluno->setNomeAluno($this->getNomeAluno());
				}
				if(!is_null($this->getEmailAluno())){
					$aluno->setEmailAluno($this->getEmailAluno());
				}
				$aluno->save();
				return true;
			} else {
				return false;
			}
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornaAlunoPorId(){
		try{
			return $this->getTable("aluno")->findOneBy('idAluno', $this->getIdAluno());
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	function getJson(){
		$array = Array();
		$array['idAluno'] = utf8_encode($this->idAluno);
		$array['nomeAluno'] = utf8_encode($this->nomeAluno);
		$array['emailAluno'] = utf8_encode($this->emailAluno);
	
		return json_encode($array);
	}
}