<?php

/**
 * Areamenor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Areamenor extends BaseAreamenor
{
	public function getIdAreaMenor() {
		return $this->idAreaMenor;
	}
	public function setIdAreaMenor($idAreaMenor) {
		$this->idAreaMenor = $idAreaMenor;
		return $this;
	}
	public function getIdAreaMaior() {
		return $this->idAreaMaior;
	}
	public function setIdAreaMaior($idAreaMaior) {
		$this->idAreaMaior = $idAreaMaior;
		return $this;
	}
	public function getNomeArea() {
		return $this->nomeArea;
	}
	public function setNomeArea($nomeArea) {
		$this->nomeArea = $nomeArea;
		return $this;
	}
	public function getAreamaior() {
		return $this->Areamaior;
	}
	public function setAreamaior($Areamaior) {
		$this->Areamaior = $Areamaior;
		return $this;
	}
	public function getDisciplina() {
		return $this->Disciplina;
	}
	public function setDisciplina($Disciplina) {
		$this->Disciplina = $Disciplina;
		return $this;
	}
}