<?php

/**
 * Assunto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Assunto extends BaseAssunto
{
	public function getIdAssunto() {
		return $this->idAssunto;
	}
	public function setIdAssunto($idAssunto) {
		$this->idAssunto = $idAssunto;
		return $this;
	}
	public function getIdDisciplina() {
		return $this->idDisciplina;
	}
	public function setIdDisciplina($idDisciplina) {
		$this->idDisciplina = $idDisciplina;
		return $this;
	}
	public function getNomeAssunto() {
		return $this->nomeAssunto;
	}
	public function setNomeAssunto($nomeAssunto) {
		$this->nomeAssunto = $nomeAssunto;
		return $this;
	}
	public function getDisciplina() {
		return $this->Disciplina;
	}
	public function setDisciplina($Disciplina) {
		$this->Disciplina = $Disciplina;
		return $this;
	}
	public function getQuestao() {
		return $this->Questao;
	}
	public function setQuestao($Questao) {
		$this->Questao = $Questao;
		return $this;
	}
	
	public function retornaTodosAssuntosPorDisciplina(){
		try{
			return $this->getTable()->findBy('idDisciplina', $this->getIdDisciplina());
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function inserirAssunto(){
		try{
			$this->save();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function alterarAssunto(){
		try{
			$assunto = Doctrine_Core::getTable('Assunto')->findOneBy('idAssunto', $this->getIdAssunto());
			if($assunto){
				if(!is_null($this->getNomeAssunto())){
					$assunto->setNomeAssunto($this->getNomeAssunto());
				}
				$assunto->save();
			}
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function deletarAssunto(){
		try{
			$a = $this->getTable()->findBy('idAssunto', $this->getIdAssunto());
			if($a){
				$a->delete();
			}
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornarAssuntoPorId(){
		try{
			return $this->getTable()->findOneBy('idAssunto', $this->getIdAssunto());
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
}