<?php

/**
 * Chamado
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Chamado extends BaseChamado
{
	public function getIdChamado() {
		return $this->idChamado;
	}
	public function setIdChamado($idChamado) {
		$this->idChamado = $idChamado;
		return $this;
	}
	public function getIdProfessor() {
		return $this->idProfessor;
	}
	public function setIdProfessor($idProfessor) {
		$this->idProfessor = $idProfessor;
		return $this;
	}
	public function getConteudo() {
		return $this->conteudo;
	}
	public function setConteudo($conteudo) {
		$this->conteudo = $conteudo;
		return $this;
	}
	public function getStatus() {
		return $this->status;
	}
	public function setStatus($status) {
		$this->status = $status;
		return $this;
	}
	public function getProfessor() {
		return $this->Professor;
	}
	public function setProfessor($Professor) {
		$this->Professor = $Professor;
		return $this;
	}
	public function getDataChamado() {
		return $this->dataChamado;
	}
	public function setDataChamado($dataChamado) {
		$this->dataChamado = $dataChamado;
		return $this;
	}
	public function getResposta() {
		return $this->resposta;
	}
	public function setResposta($resposta) {
		$this->resposta = $resposta;
		return $this;
	}
	
	public function inserirChamado(){
		try{
			$this->save();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornarChamadosAbertos(){
		try{
			return $this->getTable()->createQuery()
									->where("status <> 'F'")
									->andWhere("idProfessor = ".$_SESSION['idProfessor'])
									->execute();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornarChamadosFechados(){
		try{
			return $this->getTable()->createQuery()
									->where("status = 'F'")
									->andWhere("idProfessor = ".$_SESSION['idProfessor'])
									->execute();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function getJson(){
		try{
			$c = $this->getTable()->findOneBy('idChamado', $this->getIdChamado());
			$array = array();
			$array['idChamado'] = $c->getIdChamado();
			$array['conteudo'] = utf8_encode($c->getConteudo());
			$array['status'] = $c->getStatus();
			$array['dataChamado'] = $c->getDataChamado();
			$array['resposta'] = $c->getResposta();
			return json_encode($array);
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
}