<?php

/**
 * Disciplina
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Disciplina extends BaseDisciplina{
public function getIdDisciplina() {
		return $this->idDisciplina;
	}
	public function setIdDisciplina($idDisciplina) {
		$this->idDisciplina = $idDisciplina;
		return $this;
	}
	public function getNomeDisciplina() {
		return $this->nomeDisciplina;
	}
	public function setNomeDisciplina($nomeDisciplina) {
		$this->nomeDisciplina = $nomeDisciplina;
		return $this;
	}
	public function getEmenta() {
		return $this->Ementa;
	}
	public function setEmenta($Ementa) {
		$this->Ementa = $Ementa;
		return $this;
	}
	public function getQuestao() {
		return $this->Questao;
	}
	public function setQuestao($Questao) {
		$this->Questao = $Questao;
		return $this;
	}
	public function getTurma() {
		return $this->Turma;
	}
	public function setTurma($Turma) {
		$this->Turma = $Turma;
		return $this;
	}
	
	public function inserirDisciplina(){
		try{
			$this->save();
			return true;
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornaTodasDisciplinas(){
		try{
			$rs = $this->getTable("disciplina")->findAll();
			return $rs;
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function excluirDisciplina(){
		try{
			$disciplina = $this->getTable('disciplina')->find($this->getIdDisciplina());
			if($disciplina){
				$disciplina->delete();
				return true;
			} else {
				return false;
			}
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function atualizarDisciplina(){
		try{
			$disciplina = $this->getTable('disciplina')->find($this->getIdDisciplina());
			if($disciplina){
				if(!is_null($this->getNomeDisciplina())){
					$disciplina->setNomeDisciplina($this->getNomeDisciplina());
				}
				if(!is_null($this->getIdDisciplina())){
					$disciplina->setIdDisciplina($this->getIdDisciplina());
				}
				$disciplina->save();
				return true;
			} else {
				return false;
			}
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornaDisciplinaPorId(){
		try{
			return $this->getTable("disciplina")->findOneBy('idDisciplina', $this->getIdDisciplina());
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	function getJson(){
		$array = Array();
		$array['idDisciplina'] = utf8_encode($this->idDisciplina);
		$array['nomeDisciplina'] = utf8_encode($this->nomeDisciplina);
		
		return json_encode($array);
	}
}