<?php

/**
 * Funcionalidades
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Funcionalidades extends BaseFuncionalidades
{
	public function getIdFuncionalidades() {
		return $this->idFuncionalidades;
	}
	public function setIdFuncionalidades($idFuncionalidades) {
		$this->idFuncionalidades = $idFuncionalidades;
		return $this;
	}
	public function getIdProfessor() {
		return $this->idProfessor;
	}
	public function setIdProfessor($idProfessor) {
		$this->idProfessor = $idProfessor;
		return $this;
	}
	public function getDisco() {
		return $this->disco;
	}
	public function setDisco($disco) {
		$this->disco = $disco;
		return $this;
	}
	public function getBlog() {
		return $this->blog;
	}
	public function setBlog($blog) {
		$this->blog = $blog;
		return $this;
	}
	public function getProfessor() {
		return $this->Professor;
	}
	public function setProfessor($Professor) {
		$this->Professor = $Professor;
		return $this;
	}
}