<?php

/**
 * Instituicao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Instituicao extends BaseInstituicao{
	public function getIdInstituicao() {
		return $this->idInstituicao;
	}
	public function setIdInstituicao($idInstituicao) {
		$this->idInstituicao = $idInstituicao;
		return $this;
	}
	public function getIdProfessor() {
		return $this->idProfessor;
	}
	public function setIdProfessor($idProfessor) {
		$this->idProfessor = $idProfessor;
		return $this;
	}
	public function getNomeInstituicao() {
		return $this->nomeInstituicao;
	}
	public function setNomeInstituicao($nomeInstituicao) {
		$this->nomeInstituicao = $nomeInstituicao;
		return $this;
	}
	public function getLogradouro() {
		return $this->logradouro;
	}
	public function setLogradouro($logradouro) {
		$this->logradouro = $logradouro;
		return $this;
	}
	public function getNumero() {
		return $this->numero;
	}
	public function setNumero($numero) {
		$this->numero = $numero;
		return $this;
	}
	public function getBairro() {
		return $this->bairro;
	}
	public function setBairro($bairro) {
		$this->bairro = $bairro;
		return $this;
	}
	public function getCidade() {
		return $this->cidade;
	}
	public function setCidade($cidade) {
		$this->cidade = $cidade;
		return $this;
	}
	public function getTelContato() {
		return $this->telContato;
	}
	public function setTelContato($telContato) {
		$this->telContato = $telContato;
		return $this;
	}
	public function getMedia() {
		return $this->media;
	}
	public function setMedia($media) {
		$this->media = $media;
		return $this;
	}
	public function getTrabalha() {
		return $this->Trabalha;
	}
	public function setTrabalha($Trabalha) {
		$this->Trabalha = $Trabalha;
		return $this;
	}
	public function getTurma() {
		return $this->Turma;
	}
	public function setTurma($Turma) {
		$this->Turma = $Turma;
		return $this;
	}
	public function getFuncionamento() {
		return $this->funcionamento;
	}
	public function setFuncionamento($funcionamento) {
		$this->funcionamento = $funcionamento;
		return $this;
	}
	public function getDias() {
		return $this->dias;
	}
	public function setDias($dias) {
		$this->dias = $dias;
		return $this;
	}
	
	public function inserirInstituicao(){
		try{
			$this->save();
			return true;
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornaTodasInstituicoes(){
		try{
			$rs = $this->getTable("instituicao")->findAll();
			return $rs;
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function excluirInstituicao(){
		try{
			$professor = $this->getTable('instituicao')->find($this->getIdInstituicao());
			if($professor){
				$professor->delete();
				return true;
			} else {
				return false;
			}
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function atualizarInstituicao(){
		try{
			$instituicao = $this->getTable('instituicao')->find($this->getIdInstituicao());
			if($instituicao){
				if(!is_null($this->getNomeInstituicao())){
					$instituicao->setNomeInstituicao($this->getNomeInstituicao());
				}
				if(!is_null($this->getLogradouro())){
					$instituicao->setLogradouro($this->getLogradouro());
				}
				if(!is_null($this->getNumero())){
					$instituicao->setNumero($this->getNumero());
				}
				if(!is_null($this->getBairro())){
					$instituicao->setBairro($this->getBairro());
				}
				if(!is_null($this->getCidade())){
					$instituicao->setCidade($this->getCidade());
				}
				if(!is_null($this->getTelContato())){
					$instituicao->setTelContato($this->getTelContato());
				}
				if(!is_null($this->getMedia())){
					$instituicao->setMedia($this->getMedia());
				}
				if(!is_null($this->getFuncionamento())){
					$instituicao->setFuncionamento($this->getFuncionamento());
				}
				if(!is_null($this->getDias())){
					$instituicao->setDias($this->getDias());
				}
				$instituicao->save();
				return true;
			} else {
				return false;
			}
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornaInstituicaoPorId(){
		try{
			return $this->getTable("instituicao")->findOneBy('idInstituicao', $this->getIdInstituicao());
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function getJson(){
		$array = Array();
		$array['idInstituicao'] = utf8_encode($this->getIdInstituicao());
		$array['nomeInstituicao'] = utf8_encode($this->getNomeInstituicao());
		$array['logradouro'] = utf8_encode($this->getLogradouro());
		$array['numero'] = utf8_encode($this->getNumero());
		$array['bairro'] = utf8_encode($this->getBairro());
		$array['cidade'] = utf8_encode($this->getCidade());
		$array['telContato'] = utf8_encode($this->getTelContato());
		$array['media'] = utf8_encode($this->getMedia());
		$array['funcionamento'] = utf8_encode($this->getFuncionamento());
		$array['dias'] = utf8_encode($this->getDias());
		
		return json_encode($array);
	}
}