<?php

/**
 * Itemavaliacao
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Itemavaliacao extends BaseItemavaliacao
{
	public function getIdAvaliacao() {
		return $this->idAvaliacao;
	}
	public function setIdAvaliacao($idAvaliacao) {
		$this->idAvaliacao = $idAvaliacao;
		return $this;
	}
	public function getIdQuestao() {
		return $this->idQuestao;
	}
	public function setIdQuestao($idQuestao) {
		$this->idQuestao = $idQuestao;
		return $this;
	}
	public function getIndice() {
		return $this->indice;
	}
	public function setIndice($indice) {
		$this->indice = $indice;
		return $this;
	}
	public function getAvaliacao() {
		return $this->Avaliacao;
	}
	public function setAvaliacao($Avaliacao) {
		$this->Avaliacao = $Avaliacao;
		return $this;
	}
	public function getQuestao() {
		return $this->Questao;
	}
	public function setQuestao($Questao) {
		$this->Questao = $Questao;
		return $this;
	}
	
	public function inserirItemAvaliacao(){
		try{
			$this->save();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function excluirQuestao(){
		try{
			$q = $this->getTable()->createQuery()
								->where('idAvaliacao = '.$this->getIdAvaliacao())
								->andWhere('idQuestao = '.$this->getIdQuestao())
								->limit('1')
								->execute();
			$q[0]->delete();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function alterarIndice(){
		try{
			$q = $this->getTable()->getConnection()
							->prepare('Update itemavaliacao set indice = '.$this->getIndice().
										' where idAvaliacao = '.$this->getIdAvaliacao().
										' AND idQuestao = '.$this->getIdQuestao());
			$q->execute();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function reorganizarItens(){
		try{
			$q = $this->getTable()->createQuery()
								->where('idAvaliacao = '.$this->getIdAvaliacao())
								->orderBy('indice')
								->execute();
			$i = 1;
			foreach ($q as $q1){
				$q1->getQuestao()->getEnunciado();
				$q1->setIndice($i);
				$q1->alterarIndice();
				$i++;
			}
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}		
	}
}