<?php

/**
 * Itemcurriculo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Itemcurriculo extends BaseItemcurriculo{
	public function getIdItemCurriculo(){
		return $this->idItemCurriculo;
	}
	
	public function getProfessor(){
		return $this->idProfessor;
	}
	
	public function getTitulo(){
		return $this->titulo;
	}
	
	public function getConteudo(){
		return $this->conteudo;
	}
	
	public function getAno(){
		return $this->ano;
	}
	
	public function setIdItemCurriculo($idItemCurriculo){
		$this->idItemCurriculo = $idItemCurriculo;
	}
	
	public function setProfessor($idProfessor){
		$this->idProfessor = $idProfessor;
	}
	
	public function setTitulo($titulo){
		$this->titulo = $titulo;
	}
	
	public function setConteudo($conteudo){
		$this->conteudo = $conteudo;
	}
	
	public function setAno($ano){
		$this->ano = $ano;
	}
	
	public function inserirItemCurriculo(){
		try{
			$this->save();
			return true;
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornaTodosItensPorIdProfessor($idProfessor){
		try{
			$rs = $this->getTable('itemCurriculo')->findBy('idProfessor', $idProfessor);
			return $rs;
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function excluirItemCurriculo(){
		try{
			$item = $this->getTable('itemCurriculo')->find($this->getIdItemCurriculo());
			if($item){
				$item->delete();
				return true;
			} else {
				return false;
			}
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function atualizaItemCurriculo(){
		try{
			$item = $this->getTable('itemCurriculo')->find($this->getIdItemCurriculo());
			if($item){
				if(!is_null($this->getTitulo())){
					$item->setTitulo($this->getTitulo());
				}
				if(!is_null($this->getConteudo())){
					$item->setConteudo($this->getConteudo());
				}
				if(!is_null($this->getAno())){
					$item->setAno($this->getAno());
				}
				$item->save();
				return true;
			} else {
				return false;
			}
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornaItemCurriculoPorId(){
		try{
			$item = $this->getTable('itemCurriculo')->find($this->getIdItemCurriculo);
			return $item;
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
}