<?php

/**
 * Lembrete
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Lembrete extends BaseLembrete
{
	public function getIdLembrete() {
		return $this->idLembrete;
	}
	public function setIdLembrete($idLembrete) {
		$this->idLembrete = $idLembrete;
		return $this;
	}
	public function getDataLembrete() {
		return $this->dataLembrete;
	}
	public function setDataLembrete($dataLembrete) {
		$this->dataLembrete = $dataLembrete;
		return $this;
	}
	public function getConteudo() {
		return $this->conteudo;
	}
	public function setConteudo($conteudo) {
		$this->conteudo = $conteudo;
		return $this;
	}
	public function getIdProfessor() {
		return $this->idProfessor;
	}
	public function setIdProfessor($idProfessor) {
		$this->idProfessor = $idProfessor;
		return $this;
	}
	
	public function inserirLembrete(){
		try{
			$this->save();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornarTodosLembretes(){
		try{
			return $this->getTable()->findAll();
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function excluirLembrete(){
		try{
			$l = $this->getTable()->findOneBy('idLembrete', $this->getIdLembrete());
			if($l){
				$l->delete();
			}
		} catch (Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
}