<?php

/**
 * Professor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Professor extends BaseProfessor{

	public function getNome(){
		return $this->nomeProfessor;
	}
	
	public function getIdProfessor(){
		return $this->idProfessor;
	}
	
	public function setNome($nomeProfessor){
		$this->nomeProfessor = $nomeProfessor;
	}
	
	public function inserirProfessor(){
		try{
			$this->save();
			return true;
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornaTodosProfessores(){
		try{
			$rs = $this->getTable("professor")->findAll();
			return $rs;
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function excluirProfessor(){
		try{
			$professor = $this->getTable('professor')->find($this->getIdProfessor());
			if($professor){
				$professor->delete();
				return true;
			} else {
				return false;
			}
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function atualizaProfessor(){
		try{
			$professor = $this->getTable('professor')->find($this->getIdProfessor());
			if($professor){
				//Sobrepor os valores
				$professor->setNome($this->getNome());
				$professor->save();
				return true;
			} else {
				return false;
			}
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function retornaProfessorPorId(){
		try{
			return $this->getTable("professor")->findOneBy('idProfessor', $this->getIdProfessor());
		} catch(Doctrine_Exception $e){
			echo $e->getMessage();
		}
	}
	
	public function validarAcesso($login, $senha){
		$retorno = $this->getTable('professor')->findBySql('login = '.$login.' AND senha = '.$senha);
		if($retorno){
			return true;
		} else {
			return false;
		}
	}
}