<?php

/**
 * Trabalha
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Trabalha extends BaseTrabalha
{
	public function getIdProfessor() {
		return $this->idProfessor;
	}
	public function setIdProfessor($idProfessor) {
		$this->idProfessor = $idProfessor;
		return $this;
	}
	public function getIdInstituicao() {
		return $this->idInstituicao;
	}
	public function setIdInstituicao($idInstituicao) {
		$this->idInstituicao = $idInstituicao;
		return $this;
	}
	public function getAno() {
		return $this->ano;
	}
	public function setAno($ano) {
		$this->ano = $ano;
		return $this;
	}
	public function getProfessor() {
		return $this->Professor;
	}
	public function setProfessor($Professor) {
		$this->Professor = $Professor;
		return $this;
	}
	public function getInstituicao() {
		return $this->Instituicao;
	}
	public function setInstituicao($Instituicao) {
		$this->Instituicao = $Instituicao;
		return $this;
	}
}